services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CLARIFAI_PAT=${CLARIFAI_PAT}
      - CLARIFAI_USER_ID=${CLARIFAI_USER_ID}
      - CLARIFAI_APP_ID=${CLARIFAI_APP_ID}
      - CLARIFAI_MODEL_ID=${CLARIFAI_MODEL_ID}
      - CLARIFAI_MODEL_VERSION_ID=${CLARIFAI_MODEL_VERSION_ID}
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
    volumes:
      - .:/app